batch_size: 32
dataset_path: dataset_train_2k.db
decoder_fc1_size: 64
decoder_fc2_size: 128
encoder_fc1_size: 64
end_row: 1000
latent_dim: 100
leaky_relu_alpha: 0.2
leaky_relu_derivative_alpha: 0.01
learning_rate: 0.0001
num_epochs: 25
seed: null
start_row: 0
test_size: 0.2
use_gpu: true
