batch_size: 32
clip: null
dataset_path: dataset_train_2k.db
decoder_fc1_size: 64
decoder_fc2_size: 128
encoder_fc1_size: 64
end_row: 2000
latent_dim: 100
leaky_relu_alpha: 0.2
learning_rate: 0.00001
model_path: null
num_epochs: 25
save: False
seed: null
start_row: 0
test_size: 0.2
use_gpu: true
