adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1e-8
adam_learning_rate: 0.001
batch_size: 32
dataset_path: dataset_train_2k.db
decoder_convolution1_kernel: [3, 3]
decoder_convolution2_kernel: [3, 3]
encoder_convolution1_kernel: [3, 3]
encoder_convolution2_kernel: [3, 3]
end_row_idx: 1000
latent_dim: 100
leaky_relu_alpha: 0.2
learning_rate: 0.0001
num_epochs: 25
start_row_idx: 0
test_size: 0.2
